import = [
  "~/.config/alacritty/themes/one_nord_custom.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
padding = { x = 5, y = 5 }
opacity = 1
startup_mode = "Windowed"
dimensions = { columns = 82, lines = 24 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular"}
size = 12

[keyboard]
bindings = [
  { key = "Return", mods = "Alt", action = "ToggleFullscreen"}
]
